# action.yml
name: 'Build and Deploy .NET Function App'
description: 'Build and deploys the .NET function app to Azure'
inputs:
  credentials:
    description: 'The credentials used to login to Azure'
    required: true  
  dotnetVersion:
    description: 'The dotnet version the function is implemented'
    required: true
    default: '6.0.x'  
  packagePath:
    description: 'The path where the published function output will be stored in'
    required: false
    default: './published'
  resourceGroupName:
    description: 'The name of the resource group'
    required: true
  functionAppName:
    description: 'The name of the function app'
    required: true
  location:
    description: 'The location where the function app will be deployed'
    required: true    
runs:
  using: 'composite'
  steps:  
    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ inputs.credentials }}

    - name: 'Create Resource Group'
      uses: Cheranga/GitHubActions/createresourcegroup@master
      with:
        credentials: ${{ inputs.credentials }}
        name: ${{ inputs.resourceGroupName }}
        location: ${{ inputs.location }}      

    - name: 'Checkout Actions Repository'
      uses: actions/checkout@v2
      with:
        repository: 'Cheranga/GitHubActions'             

    - name: 'Provision Infrastructure for Function App'
      uses: azure/arm-deploy@v1
      with:
          failOnStdErr: false
          deploymentName: '${{ github.run_number }}-${{ inputs.functionAppName }}'
          resourceGroupName: ${{ inputs.resourceGroupName }}
          template: ./.github/templates/functionapp/template.bicep
          parameters: >
             sgName=sg${{ inputs.functionAppName }}