# action.yml
name: 'Create Key Vault'
description: 'Create Key Vault'
inputs:
  credentials:
    description: 'The credentials used to login to Azure'
    required: true
  keyVaultName:
    description: 'The name of the key vault'
    required: true
  resourceGroupName:
    description: 'The name of the resource group'
    required: true
  location:
    description: 'The location'
    required: true
  readAccessPrincipalList:
    description: 'The read access service principals'
    required: false 
  writeAccessPrincipalList:
    description: 'The write access service principals'
    required: false       
runs:
  using: 'composite'
  steps:
    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ inputs.credentials }}
    - name: 'Checkout Repository'
      uses: actions/checkout@v2        
    - name: 'Create Key Vault'             
      uses: azure/arm-deploy@v1
      with:
          failOnStdErr: false
          deploymentName: ${{ inputs.keyVaultName }}
          resourceGroupName: ${{ inputs.resourceGroupName }}
          template: template.bicep
          parameters: >
             keyVaultName=${{ inputs.keyVaultName }} 
             location=${{ inputs.location }} 
             readAccessPrincipalList=${{ inputs.readAccessPrincipalList }} 
             writeAccessPrincipalList=${{ inputs.writeAccessPrincipalList }} 

             