# action.yml
name: 'Create Function App Settings'
description: 'Create Function App Settings'
inputs:
  deploymentName:
    description: 'The name of the deployment'
    required: true
  resourceGroupName:
    description: 'The name of the resource group'
    required: true    
  location:
    description: 'The location of the function app'
    required: true       
  credentials:
    description: 'The credentials used to login to Azure'
    required: true
  functionAppName:
    description: 'The name of the function app'
    required: true  
  appSettings:
    description: 'The app settings of the function app'
    required: true  
runs:
  using: 'composite'
  steps:
    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ inputs.credentials }}
    - name: 'Checkout Repository'
      uses: actions/checkout@v2
      with:
        repository: 'Cheranga/GitHubActions' 
    - name: 'Create Key Vault'             
      uses: azure/arm-deploy@v1
      with:
          failOnStdErr: false
          deploymentName: ${{ inputs.deploymentName }}
          resourceGroupName: ${{ inputs.resourceGroupName }}
          template: ./.github/templates/functionappsettings/template.bicep
          parameters: >
             functionAppName=${{ inputs.functionAppName }} 
             location=${{ inputs.functionAppName }} 
             appSettings=${{ inputs.appSettings }} 

             